version: '3'

services:
  socat:
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    ports:
      - "127.0.0.1:2376:2376"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  jenkins:
    # image: jenkins/jenkins:lts
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home: